# Generated by Django 3.1.7 on 2021-04-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Reto',
            new_name='MinutosJugados',
        ),
    ]
