# Generated by Django 3.1.7 on 2021-04-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0003_auto_20210401_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edades',
            old_name='nombre2',
            new_name='nombre',
        ),
    ]
