# Generated by Django 3.1.7 on 2021-04-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0005_auto_20210402_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanenciaEnLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('permanencia', models.IntegerField()),
            ],
        ),
    ]
