# Generated by Django 3.1.7 on 2021-04-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0006_permanenciaenlinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edades',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Videojuego.usuarios'),
        ),
    ]
