# Generated by Django 3.1.7 on 2021-04-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0008_reto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='minutos_jugados',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ultimo_inicio',
        ),
    ]
