# Generated by Django 3.1.7 on 2021-04-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0009_auto_20210419_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
