# Generated by Django 3.1.7 on 2021-04-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0010_usuarios_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='datetime',
        ),
    ]
