# Generated by Django 3.1.7 on 2021-04-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0012_auto_20210422_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ultimo_inicio',
        ),
    ]
