# Generated by Django 3.1.7 on 2021-04-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0014_usuarios_ultimo_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reto',
        ),
    ]
