# Generated by Django 3.1.7 on 2021-04-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0015_delete_reto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='ultimo_inicio',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='area_fav',
            field=models.CharField(default='Quimica', max_length=10),
            preserve_default=False,
        ),
    ]
