# Generated by Django 3.1.7 on 2021-04-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0017_usuarios_ultimo_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='ultimo_inicio',
            new_name='last_login',
        ),
        migrations.CreateModel(
            name='MinijuegoQuimica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_jugado_quimica', models.IntegerField()),
                ('nivel_actual_quimica', models.IntegerField()),
                ('scoreQuimica', models.IntegerField()),
                ('intentos_por_nivel_quimica', models.IntegerField()),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Videojuego.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='MinijuegoFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_jugado_fisica', models.FloatField()),
                ('nivel_actual_fisica', models.IntegerField()),
                ('scoreFisica', models.IntegerField()),
                ('intentos_por_nivel_fisica', models.IntegerField()),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Videojuego.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='MinijuegoCompu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_jugado_compu', models.FloatField()),
                ('nivel_actual_compu', models.IntegerField()),
                ('scoreCompu', models.IntegerField()),
                ('intentos_por_nivel_compu', models.IntegerField()),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Videojuego.usuarios')),
            ],
        ),
    ]
