# Generated by Django 3.1.7 on 2021-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videojuego', '0018_auto_20210423_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edades',
            name='nombre',
        ),
        migrations.DeleteModel(
            name='PermanenciaEnLinea',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default=12345, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Edades',
        ),
    ]
